### PR TITLE
Mark img-tags with class="formula-inline" or class="formula-block"

### PR DESCRIPTION
**Pull request by holgerengels**
https://jira.xwiki.org/projects/FORMULA/issues/FORMULA-6

### CODE REVIEW

**Comment by vmassol** [comment]
Hello. Thanks for the PR! 

Have you rebuilt the project locally with Maven after your change? I'm surprised that the tests didn't need an update to reflect the change.

Thx

**Comment by vmassol** [comment]
PS: Ideally the commit should contain the JIRA id, see https://dev.xwiki.org/xwiki/bin/view/Community/DevelopmentPractices#HRule:AlwaysputaJIRAissuereferenceincommitmessages

Thx

**Comment by holgerengels** [comment]
> Have you rebuilt the project locally with Maven after your change? I'm surprised that the tests didn't need an update to reflect the change.

Hi .. well, actually not .. sorry!

**Comment by vmassol** [comment]
@holgerengels if you need help, please check https://dev.xwiki.org/xwiki/bin/view/Community/Building/

You can also drop on the Matrix #xwiki channel and we can help. If all of this is too complex, I can also spend some extra time to manually apply your PR to my local workspace and rebuild the project and fix the tests if need be (but it would be good if you could do it as you'd learn how to build some XWiki contrib project, which is needed to be able to send PRs).

Thx!

**Comment by holgerengels** [comment]
Hi Vincent,

I've created a new pull request, as I didn't succeed to add more commits to the existing pull request:

https://github.com/xwiki-contrib/macro-formula/pull/1

**Pull request closed without merging**
